name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer Dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Set Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create SQLite Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Run Tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test

    - name: Notify on Failure
      if: failure()
      runs-on: ubuntu-latest
      steps:
        - name: Send failure notification
          uses: actions/github-script@v6
          with:
            script: |
              const sgMail = require('@sendgrid/mail');
              sgMail.setApiKey(process.env.SENDGRID_API_KEY);
              const msg = {
                to: [
                  { email: 'chhit085@gmail.com' },
                  { email: 'tongmeng016@gmail.com' },
                ], // Add more recipients as needed
                from: 'nooberchhit@gmail.com', // Change to your verified sender
                subject: 'GitHub Actions Workflow Failed',
                text: `The workflow for branch ${context.payload.ref} has failed.`,
                html: `<strong>The workflow for branch ${context.payload.ref} has failed.</strong>`,
              };
              sgMail.send(msg).then(() => {
                console.log('Email sent');
              }).catch((error) => {
                console.error(error);
              });
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
